//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shtat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int ID { get; set; }
        public string Podrazd { get; set; }
        public string Otdel { get; set; }
        public string Gruppa { get; set; }
        public string Uch { get; set; }
        public string Dolj { get; set; }
        public string Sotr { get; set; }
        public string AUP { get; set; }
        public string Bts { get; set; }
        public string Kol { get; set; }
        public string Vsego { get; set; }
        public string C093107 { get; set; }
        public string VisKval { get; set; }
        public string TehVid { get; set; }
        public string HarSpec { get; set; }
        public string ZaFil { get; set; }
        public string ZaKat { get; set; }
        public string ZaStar { get; set; }
        public string OkPov { get; set; }
        public string ZaKontr { get; set; }
        public string C1748 { get; set; }
        public string DoljOk { get; set; }
        public string ProfMast { get; set; }
        public string VisDost { get; set; }
        public string Proch { get; set; }
        public string Itog { get; set; }
        public Nullable<System.DateTime> Dat { get; set; }
        public string Priznak { get; set; }
        public string OKRB { get; set; }
        public Nullable<int> PrizOtdel { get; set; }
        public Nullable<int> PrizDolj { get; set; }
    }
}
