//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shtat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shtatEntities : DbContext
    {
        public shtatEntities()
            : base("name=shtatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BazTarStavka> BazTarStavka { get; set; }
        public virtual DbSet<Doljnost> Doljnost { get; set; }
        public virtual DbSet<Gruppa> Gruppa { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<HistoryDat> HistoryDat { get; set; }
        public virtual DbSet<OKRB> OKRB { get; set; }
        public virtual DbSet<Organiz> Organiz { get; set; }
        public virtual DbSet<Otdel> Otdel { get; set; }
        public virtual DbSet<Podrazdel> Podrazdel { get; set; }
        public virtual DbSet<Razr> Razr { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uchastok> Uchastok { get; set; }
        public virtual DbSet<vacancy> vacancy { get; set; }
    }
}
