//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shtat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Razr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Razr()
        {
            this.vacancy = new HashSet<vacancy>();
        }
    
        public int IDRazr { get; set; }
        public Nullable<int> Razr1 { get; set; }
        public Nullable<int> RazrETC { get; set; }
        public Nullable<decimal> MK { get; set; }
        public Nullable<System.DateTime> Datein { get; set; }
        public Nullable<System.DateTime> Dateout { get; set; }
        public Nullable<int> Priznak { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vacancy> vacancy { get; set; }
    }
}
