//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shtat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacancy
    {
        public int IDVac { get; set; }
        public Nullable<int> IDPodrPr { get; set; }
        public Nullable<int> IDPodrOtd { get; set; }
        public Nullable<int> IDPodrPodr { get; set; }
        public Nullable<int> IDPodrUch { get; set; }
        public Nullable<int> IDDolj { get; set; }
        public Nullable<int> IDSotr { get; set; }
        public string AUP { get; set; }
        public Nullable<int> IDRazr { get; set; }
        public Nullable<int> IDStav { get; set; }
        public Nullable<decimal> Kol { get; set; }
        public Nullable<decimal> VsegoZarpl { get; set; }
        public Nullable<decimal> C0_931_07 { get; set; }
        public Nullable<decimal> KtVisKval { get; set; }
        public Nullable<decimal> KtTehVid { get; set; }
        public Nullable<decimal> KtHarSpec { get; set; }
        public Nullable<decimal> KtFilial { get; set; }
        public Nullable<decimal> KtZaKateg { get; set; }
        public Nullable<decimal> KtZaStarsh { get; set; }
        public Nullable<decimal> OkladPovish { get; set; }
        public Nullable<decimal> KtZaContract { get; set; }
        public Nullable<decimal> Post1748 { get; set; }
        public Nullable<decimal> DoljnOklad { get; set; }
        public Nullable<decimal> KtZaProfMast { get; set; }
        public Nullable<decimal> KtZaVisDostij { get; set; }
        public Nullable<decimal> KtProchaya { get; set; }
        public Nullable<decimal> Itog { get; set; }
        public Nullable<System.DateTime> Datein { get; set; }
        public Nullable<System.DateTime> Dateout { get; set; }
        public string Priznak { get; set; }
        public Nullable<int> IDOKRB { get; set; }
    
        public virtual BazTarStavka BazTarStavka { get; set; }
        public virtual Doljnost Doljnost { get; set; }
        public virtual Gruppa Gruppa { get; set; }
        public virtual OKRB OKRB { get; set; }
        public virtual Otdel Otdel { get; set; }
        public virtual Podrazdel Podrazdel { get; set; }
        public virtual Razr Razr { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Uchastok Uchastok { get; set; }
    }
}
